Mathster/Mathster/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mathster.Models;
using Mathster.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mathster.Controllers
{
    public class GameController : Controller
    {

        //MultiplikationIndexVM multiplikationIndexVM = new MultiplikationIndexVM();
        private readonly QuestionService questionService;
        public GameController(QuestionService questionService)
        {
            this.questionService = questionService;
        }

        [Route("{gametype}/{level}")]
        public IActionResult Index(Level level, GameType gameType)
        {
            var model = questionService.GetGameIndexVM(level, gameType);

            return View(model);
        }
        [HttpPost]
        [Route("{gametype}/nextquestion/{level}/{clickedIndex}")]
        public GameNewQuestionVM NewQuestion(Level level, int? clickedIndex, GameType gameType)
        {
            return questionService.GetNewQuestion(level, clickedIndex, HttpContext, gameType);
            
           


        }
    }
}

Mathster/Mathster/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mathster.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        [Route("start")]
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Mathster/Mathster/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mathster.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mathster.Controllers
{
    public class InfoController : Controller
    {
        private readonly InfoRepository infoRepository;
        public InfoController(InfoRepository infoRepository)
        {
            this.infoRepository = infoRepository;
        }

        [Route("{gametype}/info")]
        public IActionResult Index(GameType gameType)
        {
            var model = infoRepository.GetInfo(gameType);

            return View(model);
        }
    }
}

Mathster/Mathster/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mathster.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mathster.Controllers
{
    public class VideoController : Controller
    {
        private readonly VideoRepository videoRepository;
        public VideoController( VideoRepository videoRepository)
        {
            this.videoRepository = videoRepository;
        }

        [Route("{gametype}/video")]
        public IActionResult Index(GameType gameType)
        {
            var model = videoRepository.GetVideo(gameType);

            return View(model);
        }
    }
}

Mathster/Mathster/Views/Home/Index.cshtml
@using Mathster.Models

<div class="container" id="container">
    <div class="mathster slide-left" id="mathster">
        <img class="mathsterLogo" src="~/ropelogo.png" />
        

    </div>

    <div class="row">
        <div class="menuChoice wrapper" id="addition">
            <i class="fas fa-plus"></i>
            <ul id="plusList">
                <li><a class="easyA" asp-controller="Game" asp-route-level="@nameof(Level.Easy)" asp-route-gametype="@nameof(GameType.Addition)"></a></li>
                <li><a class="mediumA" asp-controller="Game" asp-route-level="@nameof(Level.Medium)" asp-route-gametype="@nameof(GameType.Addition)"></a></li>
                <li><a class="hardA" asp-controller="Game" asp-route-level="@nameof(Level.Hard)" asp-route-gametype="@nameof(GameType.Addition)"></a></li>
                <li class="hideInMobile"><a class="video" asp-controller="Video" asp-route-gametype="@nameof(GameType.Addition)"></a></li>
                <li class="hideInMobile"><a class="info" asp-controller="Info" asp-route-gametype="@nameof(GameType.Addition)"></a></li>

            </ul>
        </div>

        <div class="menuChoice wrapper" id="subtraction">
            <i class="fas fa-minus"></i>
            <ul id="minusList">
                <li><a class="easyA" asp-controller="Game" asp-route-level="@nameof(Level.Easy)" asp-route-gametype="@nameof(GameType.Subtraction)"></a></li>
                <li><a class="mediumA" asp-controller="Game" asp-route-level="@nameof(Level.Medium)" asp-route-gametype="@nameof(GameType.Subtraction)"></a></li>
                <li><a class="hardA" asp-controller="Game" asp-route-level="@nameof(Level.Hard)" asp-route-gametype="@nameof(GameType.Subtraction)"></a></li>
                <li class="hideInMobile"><a class="video" asp-controller="Video" asp-route-gametype="@nameof(GameType.Subtraction)"></a></li>
                <li class="hideInMobile"><a class="info" asp-controller="Info" asp-route-gametype="@nameof(GameType.Subtraction)"></a></li>

            </ul>
        </div>
        <div class="menuChoice wrapper" id="multiplication">
            <i class="fas fa-times"></i>
            <ul id="multiList">
                <li><a class="easyA" asp-controller="Game" asp-route-level="@nameof(Level.Easy)" asp-route-gametype="@nameof(GameType.Multiplication)"></a></li>
                <li><a class="mediumA" asp-controller="Game" asp-route-level="@nameof(Level.Medium)" asp-route-gametype="@nameof(GameType.Multiplication)"></a></li>
                <li><a class="hardA" asp-controller="Game" asp-route-level="@nameof(Level.Hard)" asp-route-gametype="@nameof(GameType.Multiplication)"></a></li>
                <li class="hideInMobile"><a class="video" asp-controller="Video" asp-route-gametype="@nameof(GameType.Multiplication)"></a></li>
                <li class="hideInMobile"><a class="info" asp-controller="Info" asp-route-gametype="@nameof(GameType.Multiplication)"></a></li>

            </ul>
        </div>

        <div class="menuChoice wrapper" id="division">
            <div class="slash"></div>
            <ul id="divList">
                <li><a class="easyA" asp-controller="Game" asp-route-level="@nameof(Level.Easy)" asp-route-gametype="@nameof(GameType.Division)"></a></li>
                <li><a class="mediumA" asp-controller="Game" asp-route-level="@nameof(Level.Medium)" asp-route-gametype="@nameof(GameType.Division)"></a></li>
                <li><a class="hardA" asp-controller="Game" asp-route-level="@nameof(Level.Hard)" asp-route-gametype="@nameof(GameType.Division)"></a></li>
                <li class="hideInMobile"><a class="video" asp-controller="Video" asp-route-gametype="@nameof(GameType.Division)"></a></li>
                <li class="hideInMobile"><a class="info" asp-controller="Info" asp-route-gametype="@nameof(GameType.Division)"></a></li>
            </ul>
        </div>
    </div>
    <div class="squirrelDiv">
        <div class="menuChoice squirrel" id="squirrel">
            <img src="~/ekorrenew.png" />
        </div>
    </div>
</div>

<script src="~/Js/MainMenu.js"></script>
<link href="~/Scripts/StartPage.css" rel="stylesheet" />
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.0.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">

<script>
    $(document).ready(function () {
        loadPage();
    });
</script>